import { readFile, writeFile } from 'node:fs/promises';
import { fetchUploads } from '../src/archive.js';
import { validFeed } from '../src/youtube.js';

const path = new URL('../src/youtube-snapshot.json', import.meta.url);
try {
  const response = await fetch('https://www.ai-automation-station.com/api/youtube', { signal: AbortSignal.timeout(8000) });
  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  const feed = await response.json();
  if (!validFeed(feed)) throw new Error('Invalid YouTube feed');
  await writeFile(path, `${JSON.stringify(feed, null, 2)}\n`);
  console.log('Updated the latest-video snapshot.');
} catch (error) {
  if (!validFeed(JSON.parse(await readFile(path, 'utf8')))) throw new Error('No usable video snapshot', { cause: error });
  console.warn(`Using the saved video snapshot: ${error.message}`);
}

// Every upload, for /api/videos to serve while the YouTube API is unreachable. Keeps the saved copy on failure.
const uploadsPath = new URL('../src/uploads-snapshot.js', import.meta.url);
try {
  if (!process.env.YOUTUBE_API_KEY) throw new Error('YOUTUBE_API_KEY is not set');
  const uploads = await fetchUploads(process.env.YOUTUBE_API_KEY);
  if (!uploads.length) throw new Error('No public uploads returned');
  await writeFile(uploadsPath, `// Generated by scripts/refresh-videos.js on each build.\nexport const uploads = [\n${uploads.map(video => JSON.stringify(video)).join(',\n')},\n];\n`);
  console.log(`Updated the uploads snapshot (${uploads.length} videos).`);
} catch (error) {
  console.warn(`Using the saved uploads snapshot: ${error.message}`);
}
